//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SushkovPW5.BDmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trailer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trailer()
        {
            this.TrailerDriver = new HashSet<TrailerDriver>();
        }
    
        public int ID { get; set; }
        public string CarBrand { get; set; }
        public string CarNumb { get; set; }
        public string CarCompany { get; set; }
        public int Carrying { get; set; }
        public decimal FuelConsum { get; set; }
        public decimal Lenght { get; set; }
        public decimal DelieveryCost { get; set; }
        public Nullable<int> Exp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrailerDriver> TrailerDriver { get; set; }
    }
}
